name: "Deploy Website to S3"
description: "Builds and deploys a React website to S3"

inputs:
  s3-prefix:
    description: "S3 folder/prefix where files should be uploaded (e.g., 'charm' or 'charm-staging')"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  s3-bucket:
    description: "S3 bucket name"
    required: true
    default: "cdn.bighelp.ai"
  build-env:
    description: "Build environment (staging or production)"
    required: true
  sentry-auth-token:
    description: "Sentry authentication token for source maps upload"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout app repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "20"

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build app
      shell: bash
      run: S3_PREFIX=${{ inputs.s3-prefix }} VITE_BUILD_ENV=${{ inputs.build-env }} VITE_USE_CDN=true SENTRY_AUTH_TOKEN=${{ inputs.sentry-auth-token }} node_modules/.bin/vite build

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: dist/
        DEST_DIR: ${{ inputs.s3-prefix }}
        AWS_S3_BUCKET: ${{ inputs.s3-bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
